// <auto-generated />
namespace Mvc5CurdDatebaseAndCodeFirstApproch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitialAddtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialAddtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202412140729152_InitialAddtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
